validation: sovereign
version: 1
accounts:
- name: alice
  coins:
  - 20000token
  - 200000000stake
- name: bob
  coins:
  - 10000token
  - 100000000stake
- name: frank
  coins: [10000token, 100000000stake]
  mnemonic: struggle since inmate safe logic kite tag web win stay security wonder
- name: Dave
  coins: [10000token, 100000000stake]
  mnemonic: mask grab pass attract expire gauge often ritual basic control pencil turkey


faucet:
  name: bob
  coins:
  - 5token
  - 100000stake
client:
  typescript:
    path: ts-client
  composables:
    path: vue/src/composables
  openapi:
    path: docs/static/openapi.yml
validators:
- name: alice
  bonded: 100000000stake
